[asset.crane]
repo = "google/go-containerregistry"
version = ">=0.20.6"
platform."linux/amd64" = "go-containerregistry_Linux_x86_64.tar.gz"
platform."darwin/arm64" = "go-containerregistry_Darwin_arm64.tar.gz"
platform."darwin/amd64" = "go-containerregistry_Darwin_x86_64.tar.gz"
executable = true
destination = "assets/crane"
extract.globs = [
    "crane"
]
extract.flatten = true

[asset.oras]
repo = "oras-project/oras"
version = ">=1.3.0"
platform."linux/amd64" = "oras_{version}_linux_amd64.tar.gz"
platform."darwin/arm64" = "oras_{version}_darwin_arm64.tar.gz"
platform."darwin/amd64" = "oras_{version}_darwin_amd64.tar.gz"
executable = true
destination = "assets/oras"
extract.globs = [
    "oras"
]
extract.flatten = true

[asset.cosign]
repo = "sigstore/cosign"
version = "==2.6.1"
platform."darwin/amd64" = "cosign-darwin-amd64"
platform."darwin/arm64" = "cosign-darwin-arm64"
platform."linux/amd64" = "cosign-linux-amd64"
platform."windows/amd64" = "cosign-windows-amd64.exe"
executable = true
destination = "assets/cosign"
